module Grad; module Pic

  def self.print
    puts <<-GRADPIC
........................................................................................................................
........................................................................................................................
..................................................................................I.....................................
........................................................................+.NZNNNNMMM$$I,. ...............................
................................................................ODNZMNMNMNM8$?IZDMMO8D8Z7?.. ...........................
................................................................8ZO$8ZMMMMMNMMDMNM$8OZ$8DDZ7I...........................
................................................................8ZDD8D$8$O$NIM7NNNN$88D8$$D78ZII........................
................................................................DZ888NNNZ8$DIMIN7$OD8O$O88OZ$888ZI?.....................
...............................................................?O$777MINON8NN8DD$MI$$O888ZZO88OZZDD8ZI,.................
................................................~.:=.7$........88NODZM8NDZM8DNNNNNN88OZ$ZDN88$O888Z$888Z7,..............
.............................................~????+??++?++++?I+=I7$DMNNNNNNMNNNNMNMNNMN8DOZODD88ZZ8D8OZO8887I...........
.........................................=+:::~?MMMMND8O$II++:M+:,MMNZ7$NNNNNNNNNNNNND8O8DO88Z$Z8D8OZ8DDO$8ZZ~..........
......................................MNNND8DD7O888OOO$$I+~N..:$I+DDDDN7MMMMMNNNMNNNND88DODDDD8OOZ$ZDD8Z$DD$$...........
..................................I..~M+++++?DMDDDDD88Z$I=,8.N,Z7?MMMDD$D888OZOOOZZ$$7$7$$88DDDNDNZ8OZ$8D88ZZ...........
..................................7..N?++++++IDDDNNDOO$I+~8..I7OZI++NDD7MMMMMMMN.NNNNNNNNNNM88DDDDDNDMO8Z$8ZZ...........
..................................$.=M??????MMMND8ZO8NNMMMM..ONZNN?+MDD$.DNMMMMMMMMM$,DNNNNNNMO8DD8DNNNDNN$$8...........
...........................,+$IIIIII????+~=:::,:~==?+?II?++7NIOMMMM$MNMZ..,NNMMMMMMMMMMMDD8~N,8,O8888DDDNNNNN...........
.....................~77II????II??+=~:~,=I$777$I7777$$Z$$$$ZZ7ZOOZZZOOZZ.....INNMMMMMMMMMMNMMMNMMMZOO888DDNND...........
..................7?I?I7I??$I???+:,~II77II7II7$777I$$Z$$7$$$Z$ZOOOOZZN8Z......~OOOOOO8OOOOOOOZ$??7Z8ZOOO88DD7...........
................$?I$I77II$$$7$Z,$ZZZ$7I77$77777III$7$7$$$$$ZZ$OOOZZO$$Z$....8O$7$7$$77?$$777$$7ZZZOO88$OO88O............
................N7MM$MNMM7MMMIZOZ$$$78M$NMZDMOM7DMZMZDM7$$Z$$$$ZZ8ZZOZOZ....N8ZOZZOZZZIZZZOZZZOOOO8D8DDN7O=.............
................DOMN$MMMMOMMMII$$$$$7DMZDMZNM8M$DMZMZ8M$ZODDZ$ZOZOOOOOZ$....NN8OO888D8IO8DDD8DD8D8DNDDND+...............
...........7I$77N$MM$MMMM$MMMII+?+?7$I=?????????7?I77ZZ$7I7$$$$O8O8OOZO$7$7$$888O+?D888D8??+I?$$Z$I?I7??III?~...........
...........,~$.OD7MMZMMMM$MMMI7OD.8M=8MZZ8DNNNNNNNNNNNNDO88888D7O888DOOZOOOO7$$$777$$?7$77?+ZDNNNNNNNNDDDNMMND7.........
............D...N$MM$MMMM$MMM7IZ. ,D+NDZ$OONNNNNNNDNDNNMD888888D$88O888ONMNNDDD88O88DDNN8OOOOZ$8NNNMDZZ77ZO8NNM8,.......
............N8.?NZMM$MMNNNMMNIIZ. .NDDZDDDDNNNMNNNO888$88ODDDD88O$N8DNNONDNDDDD+NNNNNNMDOOZ$I7$$ZMMNDOZ?III$DDNND,......
.....NMNNMN8MMDOZMMMZMMMMDD8O$7O8.OD87DDD8NNMNDO7IO?$+I=+I$ZDD8887888D8~$$$O$ZIDNI8Z$77NDI7?IZ$$7ONN8~7I7O8Z7DD8OO......
.....NMNMMMMNMNMMMMNMMMMMNNNMMNMMMMZZDDD8MMD8ZZ:IIZ??$777II7$8D88D7DDDD$=8$8$DZOZ$DOZZZN8$=7ONND8$ODZ?I7DNDDOZ8OOZ......
.....MMMNMMMMMMMMNNMMMMMMMNMMMNMMMMMMMMNMMNDZZI??I?7ODDMNO$77ODN88O$DDN$$=ZZ$DZOZZD88OZNIO7ONNDDDO77DI7ODDNDD$~..,......
.....MNDDNMNMMMMMNMMMMMMMMNNMMMMMMMMNNMMMMDZO??ZII7DDD888DN$7ZDD888$NNN$7$=ZZ8ZZOODD8OON7O$DNNDNDD7O7IINMDDDDZ=:::......
.............Z,.NDNNNNMMMMMMMMMMMMMMMNNMMDZ$++I~I$NDD88D8NDD7?D888NMII$$$ZD8ODOOOON88OOD$+ZD8DN8D8$D++IDNDD88Z+~~~~~~~~~
.............I:,I8NNNDDNMMMMMNNNNMMMMMMM8Z$8IIZI7DDNDND8DDDD87OD8DMNMNMNMD88$DNMMMMMNNN$$7Z8DDDO8DIOII7NDOO8D$+=========
...............Z7MD8ND8MMMMMMMMMMMMMMMMMNOZ8OI=?$NDNND88DDD8D78DN8NMNNMMDDMNNDD8NMMNMNN+$OZD8OOD8DIN87?O8OO8D7++======:,
.................DDMM8DMMMMNMNNMMMMMMMMMDOON77$+7D8ND8DDODOOD7Z8DMDNNMNDDNINNDND888DDNMN$7IDDDO8D$8DM$778DDD7Z++++~::,..
.................MND8ND8DMMNNNNMMMN8D8??N88DZ+I+$ND8DOD8O888ZIZN8NDD88DDN777NDNNNDNZONNM$O7$DDDNZINND7$$I$Z7DIII???=::~~
...............,,,DNN8D88DNMMMMMMNDDDIIIN8D8$DZ?$NDD8DOOO8ZD$?8DNNNNNDNOO88DDDNNNNNNNMDNOZO7IZZ7ODONNDZO8O8D777I+~,:,,,,
....,,,,,,,,,,:?IIINDM8DDO8DDNDD8DNMI7778NDDO8???ZNODZOODODOI8N88DDDDNNNNNNNMNMMMMNNNNNNNN8OO$88NNNNNDNMD8+~~~::::::::::
,,,,,,,,,,,:+I77777$NNOND8DD888NDNO$ZZZZZNNDDOZ$?IZN8DD8DNZ$OD8DDDDDDDDDNNNNNNNNNNNMMNMMNNNO8D8=~~~~~~~~~:::::::::::::::
,,,:?77777I+~+77$$$$$$8D8NDDDDDMD88DDDDDDDDNN8OZ$?I$ZO88O$IODDDDDDDDDDDDDDDD8888O$?~~~~~~~~~~~~~:::::::::::::::::::::::,
,,,,,,::::+7$$$ZZZZZO8DDNNNNNNMNNNNNNNNNNNNNDNZODZ$I?III?$NNDDDDDDZ=::~:~~:~:~~~~~~~:::::::::::::::::::::::::::,,,,,,,,,
,,,,,::::::::::~~=$O888888DDDDDDDDDNNNNNNNNNNNNMDN8ODZDZD8NDD887=~~~~~~~~::::::::::::::::::::::::::::::,,,,,,,,,,,,,,,,,
,,,,,:::::::::::::::~~~~:=7O8888DD8Z+::::+DNNNNNNM8NNDDDN7=:~:::::::::::::::::::::::::::::,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,::::::::::::::::::::::~~::~?ZO?:::::::::~=~~:~:::::::::::::::::::::::::::,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,::::::::::::::::::::::::::::::::::::::::::::::::,::::,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
    GRADPIC
  end
end; end

